<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\Category;
use App\Models\SubCategory;

class EventsSeeder extends Seeder
{
    /**
     * Seed the events table with realistic map data.
     *
     * Creates events across multiple European cities with:
     * - Different categories (music, dance, theatre, nightlife, film)
     * - Past events, currently live events, and upcoming events
     * - Realistic coordinates for map visualization
     */
    public function run(): void
    {
        $now = Carbon::now();

        $events = [
        // 🎭 TALENT 类别 (10个事件)
        [
            'title' => 'Broadway Star Showcase',
            'description' => 'An exclusive evening featuring Tony Award-winning actors and actresses performing monologues from classic Broadway plays.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'actor',
            'price' => 65.00,
            'dresscode' => 'evening elegant',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(3)->setHour(19),
            'end_datetime' => $now->copy()->addDays(3)->setHour(22),
            'city' => 'New York',
            'address' => 'Broadway Theater District, New York, NY',
            'latitude' => 40.7614,
            'longitude' => -73.9834,
        ],
        [
            'title' => 'International Celebrity Gala',
            'description' => 'Red carpet event with A-list celebrities for charity fundraising with live performances.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'celebrity',
            'price' => 250.00,
            'dresscode' => 'black tie',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(10)->setHour(20),
            'end_datetime' => $now->copy()->addDays(10)->setHour(23),
            'city' => 'Los Angeles',
            'address' => 'Hollywood Boulevard, Los Angeles, CA',
            'latitude' => 34.1016,
            'longitude' => -118.3387,
        ],
        [
            'title' => 'Cirque du Soleil: Aerial Artists',
            'description' => 'Breathtaking circus performance featuring world-class acrobats and aerialists.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'circus artist',
            'price' => 85.00,
            'dresscode' => 'smart casual',
            'min_age' => 8,
            'start_datetime' => $now->copy()->addDays(5)->setHour(20),
            'end_datetime' => $now->copy()->addDays(5)->setHour(22),
            'city' => 'Las Vegas',
            'address' => 'Bellagio Hotel, Las Vegas, NV',
            'latitude' => 36.1126,
            'longitude' => -115.1765,
        ],
        [
            'title' => 'Stand-up Comedy Night',
            'description' => 'Top comics from Netflix specials performing live with new material.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'comic',
            'price' => 35.00,
            'dresscode' => 'casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(2)->setHour(21),
            'end_datetime' => $now->copy()->addDays(2)->setHour(23),
            'city' => 'Chicago',
            'address' => 'The Laugh Factory, Chicago, IL',
            'latitude' => 41.8954,
            'longitude' => -87.6327,
        ],
        [
            'title' => 'Contemporary Dance Ensemble',
            'description' => 'Award-winning dance company presenting innovative choreography.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'dancer',
            'price' => 45.00,
            'dresscode' => 'smart casual',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(7)->setHour(19),
            'end_datetime' => $now->copy()->addDays(7)->setHour(21),
            'city' => 'San Francisco',
            'address' => 'War Memorial Opera House, San Francisco, CA',
            'latitude' => 37.7793,
            'longitude' => -122.4192,
        ],
        [
            'title' => 'DJ Festival Weekend',
            'description' => 'Three-day electronic music festival featuring top international DJs.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'dj/vj',
            'price' => 120.00,
            'dresscode' => 'festival wear',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(14)->setHour(16),
            'end_datetime' => $now->copy()->addDays(16)->setHour(23),
            'city' => 'Miami',
            'address' => 'Bayfront Park, Miami, FL',
            'latitude' => 25.7753,
            'longitude' => -80.1889,
        ],
        [
            'title' => 'Magic & Illusion Extravaganza',
            'description' => 'World-famous magicians performing impossible feats of illusion.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'magician/illusionist',
            'price' => 55.00,
            'dresscode' => 'smart casual',
            'min_age' => 10,
            'start_datetime' => $now->copy()->addDays(4)->setHour(19),
            'end_datetime' => $now->copy()->addDays(4)->setHour(21),
            'city' => 'Los Angeles',
            'address' => 'Magic Castle, Hollywood, CA',
            'latitude' => 34.1030,
            'longitude' => -118.3423,
        ],
        [
            'title' => 'Symphony Orchestra Performance',
            'description' => 'Classical music concert featuring renowned musicians and soloists.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'musician',
            'price' => 60.00,
            'dresscode' => 'formal',
            'min_age' => 8,
            'start_datetime' => $now->copy()->addDays(6)->setHour(20),
            'end_datetime' => $now->copy()->addDays(6)->setHour(22),
            'city' => 'London',
            'address' => 'Royal Albert Hall, London, UK',
            'latitude' => 51.5010,
            'longitude' => -0.1772,
        ],
        [
            'title' => 'Broadway Singers Showcase',
            'description' => 'Tony Award-winning vocalists performing Broadway hits.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'singer',
            'price' => 50.00,
            'dresscode' => 'evening wear',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(8)->setHour(20),
            'end_datetime' => $now->copy()->addDays(8)->setHour(22),
            'city' => 'New York',
            'address' => 'Carnegie Hall, New York, NY',
            'latitude' => 40.7650,
            'longitude' => -73.9799,
        ],
        [
            'title' => 'Street Performer Festival',
            'description' => 'Annual gathering of the best street performers from around the world.',
            'category_slug' => 'talent',
            'subcategory_slug' => 'other',
            'price' => null,
            'dresscode' => 'casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(12)->setHour(11),
            'end_datetime' => $now->copy()->addDays(12)->setHour(20),
            'city' => 'Edinburgh',
            'address' => 'Royal Mile, Edinburgh, Scotland',
            'latitude' => 55.9504,
            'longitude' => -3.1883,
        ],

        // 🏛️ VENUE 类别 (8个事件)
        [
            'title' => 'Craft Beer Tasting Night',
            'description' => 'Sample rare craft beers from local breweries in a cozy bar setting.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'bar',
            'price' => 25.00,
            'dresscode' => 'casual',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(1)->setHour(18),
            'end_datetime' => $now->copy()->addDays(1)->setHour(23),
            'city' => 'Portland',
            'address' => 'Pearl District Breweries, Portland, OR',
            'latitude' => 45.5231,
            'longitude' => -122.6765,
        ],
        [
            'title' => 'High-Stakes Poker Tournament',
            'description' => 'Professional poker tournament with $100,000 prize pool.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'casino',
            'price' => 1000.00,
            'dresscode' => 'smart casual',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(15)->setHour(14),
            'end_datetime' => $now->copy()->addDays(15)->setHour(23),
            'city' => 'Las Vegas',
            'address' => 'Bellagio Casino, Las Vegas, NV',
            'latitude' => 36.1129,
            'longitude' => -115.1765,
        ],
        [
            'title' => 'Indie Film Premiere',
            'description' => 'Exclusive premiere of award-winning independent film with director Q&A.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'cinema',
            'price' => 20.00,
            'dresscode' => 'smart casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(5)->setHour(19),
            'end_datetime' => $now->copy()->addDays(5)->setHour(22),
            'city' => 'Los Angeles',
            'address' => 'Arclight Hollywood, Los Angeles, CA',
            'latitude' => 34.1020,
            'longitude' => -118.3410,
        ],
        [
            'title' => 'Government Open House',
            'description' => 'Annual public open house at historic government building.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'government',
            'price' => null,
            'dresscode' => 'smart casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(9)->setHour(10),
            'end_datetime' => $now->copy()->addDays(9)->setHour(16),
            'city' => 'Washington D.C.',
            'address' => 'White House Visitors Center, Washington D.C.',
            'latitude' => 38.8977,
            'longitude' => -77.0365,
        ],
        [
            'title' => 'Conference Hall Expo',
            'description' => 'Technology and innovation expo in major conference hall.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'hall',
            'price' => 35.00,
            'dresscode' => 'business casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(11)->setHour(9),
            'end_datetime' => $now->copy()->addDays(11)->setHour(18),
            'city' => 'San Francisco',
            'address' => 'Moscone Center, San Francisco, CA',
            'latitude' => 37.7839,
            'longitude' => -122.4014,
        ],
        [
            'title' => 'Luxury Hotel Gala Dinner',
            'description' => 'Five-course gourmet dinner at 5-star hotel ballroom.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'hotel',
            'price' => 150.00,
            'dresscode' => 'formal',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(7)->setHour(19),
            'end_datetime' => $now->copy()->addDays(7)->setHour(23),
            'city' => 'New York',
            'address' => 'The Plaza Hotel, New York, NY',
            'latitude' => 40.7644,
            'longitude' => -73.9747,
        ],
        [
            'title' => 'Stadium Rock Concert',
            'description' => 'Major rock band performing at 50,000 seat stadium.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'stadium',
            'price' => 75.00,
            'dresscode' => 'concert wear',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(20)->setHour(19),
            'end_datetime' => $now->copy()->addDays(20)->setHour(23),
            'city' => 'Los Angeles',
            'address' => 'SoFi Stadium, Los Angeles, CA',
            'latitude' => 33.9535,
            'longitude' => -118.3390,
        ],
        [
            'title' => 'Historic Theatre Restoration Gala',
            'description' => 'Fundraiser for the restoration of a historic theatre venue.',
            'category_slug' => 'venue',
            'subcategory_slug' => 'theatre',
            'price' => 100.00,
            'dresscode' => 'formal',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(14)->setHour(18),
            'end_datetime' => $now->copy()->addDays(14)->setHour(23),
            'city' => 'Paris',
            'address' => 'Palais Garnier, Paris, France',
            'latitude' => 48.8719,
            'longitude' => 2.3316,
        ],

        // 🌃 NIGHTLIFE 类别 (12个事件)
        [
            'title' => 'After Hours Jazz Club',
            'description' => 'Late-night jazz session in intimate club setting.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'after midnight bar',
            'price' => 30.00,
            'dresscode' => 'smart casual',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(2)->setHour(1),
            'end_datetime' => $now->copy()->addDays(2)->setHour(4),
            'city' => 'New Orleans',
            'address' => 'Frenchmen Street, New Orleans, LA',
            'latitude' => 29.9631,
            'longitude' => -90.0579,
        ],
        [
            'title' => '24-Hour Diner Experience',
            'description' => 'Late-night dining with live entertainment until sunrise.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'after midnight restaurant',
            'price' => 25.00,
            'dresscode' => 'casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(3)->setHour(2),
            'end_datetime' => $now->copy()->addDays(3)->setHour(6),
            'city' => 'New York',
            'address' => 'Times Square District, New York, NY',
            'latitude' => 40.7580,
            'longitude' => -73.9855,
        ],
        [
            'title' => 'Midnight Cabaret Show',
            'description' => 'Risqué cabaret performance for mature audiences.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'after midnight show',
            'price' => 40.00,
            'dresscode' => 'dressy',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(5)->setHour(0),
            'end_datetime' => $now->copy()->addDays(5)->setHour(2),
            'city' => 'Berlin',
            'address' => 'Kurfürstendamm, Berlin, Germany',
            'latitude' => 52.5027,
            'longitude' => 13.3181,
        ],
        [
            'title' => 'Festival After Party',
            'description' => 'Exclusive after party for festival attendees.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'after party',
            'price' => 35.00,
            'dresscode' => 'festival wear',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(8)->setHour(23),
            'end_datetime' => $now->copy()->addDays(9)->setHour(4),
            'city' => 'Austin',
            'address' => '6th Street, Austin, TX',
            'latitude' => 30.2672,
            'longitude' => -97.7431,
        ],
        [
            'title' => 'Indie Film Night Screening',
            'description' => 'Midnight screening of cult classic films.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'cinema',
            'price' => 15.00,
            'dresscode' => 'casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(4)->setHour(23),
            'end_datetime' => $now->copy()->addDays(5)->setHour(2),
            'city' => 'Los Angeles',
            'address' => 'New Beverly Cinema, Los Angeles, CA',
            'latitude' => 34.0837,
            'longitude' => -118.3610,
        ],
        [
            'title' => 'Latin Dance Social',
            'description' => 'Salsa and bachata dancing with live band.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'dance',
            'price' => 20.00,
            'dresscode' => 'dance attire',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(6)->setHour(21),
            'end_datetime' => $now->copy()->addDays(7)->setHour(2),
            'city' => 'Miami',
            'address' => 'Little Havana, Miami, FL',
            'latitude' => 25.7667,
            'longitude' => -80.2000,
        ],
        [
            'title' => 'Ballroom Dance Night',
            'description' => 'Formal ballroom dancing with professional instructors.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'dancing',
            'price' => 25.00,
            'dresscode' => 'formal',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(10)->setHour(20),
            'end_datetime' => $now->copy()->addDays(10)->setHour(23),
            'city' => 'London',
            'address' => 'Mayfair Ballroom, London, UK',
            'latitude' => 51.5074,
            'longitude' => -0.1278,
        ],
        [
            'title' => 'Broadway Dinner Theater',
            'description' => 'Dinner and Broadway-style show performance.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'dinner show',
            'price' => 95.00,
            'dresscode' => 'smart casual',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(12)->setHour(19),
            'end_datetime' => $now->copy()->addDays(12)->setHour(22),
            'city' => 'New York',
            'address' => 'Theater District, New York, NY',
            'latitude' => 40.7590,
            'longitude' => -73.9845,
        ],
        [
            'title' => 'Techno DJ Marathon',
            'description' => '8-hour techno DJ set in underground club.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'dj/vj session',
            'price' => 30.00,
            'dresscode' => 'club wear',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(7)->setHour(22),
            'end_datetime' => $now->copy()->addDays(8)->setHour(6),
            'city' => 'Berlin',
            'address' => 'Berghain, Berlin, Germany',
            'latitude' => 52.5112,
            'longitude' => 13.4428,
        ],
        [
            'title' => 'Techno Underground',
            'description' => 'Deep techno beats at one of Amsterdam\'s most famous underground clubs.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'nightclub',
            'price' => 25.00,
            'dresscode' => 'black preferred',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(1)->setHour(23),
            'end_datetime' => $now->copy()->addDays(2)->setHour(6),
            'city' => 'Amsterdam',
            'address' => 'Zeeburgerpad 53, 1019 AA Amsterdam',
            'latitude' => 52.3676,
            'longitude' => 4.9376,
            'night' => true,
        ],
        [
            'title' => 'Karaoke Championship',
            'description' => 'Competitive karaoke with cash prizes.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'karaoke',
            'price' => 10.00,
            'dresscode' => 'casual',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(3)->setHour(20),
            'end_datetime' => $now->copy()->addDays(3)->setHour(23),
            'city' => 'Tokyo',
            'address' => 'Shinjuku District, Tokyo, Japan',
            'latitude' => 35.6895,
            'longitude' => 139.6917,
        ],
        [
            'title' => 'Ladies Night VIP',
            'description' => 'Exclusive ladies night with complimentary drinks.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'ladies night',
            'price' => 15.00,
            'dresscode' => 'dressy',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(5)->setHour(21),
            'end_datetime' => $now->copy()->addDays(6)->setHour(2),
            'city' => 'Las Vegas',
            'address' => 'The Strip, Las Vegas, NV',
            'latitude' => 36.1147,
            'longitude' => -115.1728,
        ],
        [
            'title' => 'Nightclub Opening Party',
            'description' => 'Grand opening of luxury nightclub.',
            'category_slug' => 'nightlife',
            'subcategory_slug' => 'nightclub',
            'price' => 50.00,
            'dresscode' => 'fashion forward',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(15)->setHour(22),
            'end_datetime' => $now->copy()->addDays(16)->setHour(4),
            'city' => 'Miami',
            'address' => 'South Beach, Miami, FL',
            'latitude' => 25.7617,
            'longitude' => -80.1918,
        ],

        // 🎬 FILM 类别 (10个事件)
        [
            'title' => 'Marvel Action Marathon',
            'description' => 'Back-to-back screening of Marvel cinematic universe films.',
            'category_slug' => 'film',
            'subcategory_slug' => 'action',
            'price' => 35.00,
            'dresscode' => 'casual',
            'min_age' => 13,
            'start_datetime' => $now->copy()->addDays(4)->setHour(12),
            'end_datetime' => $now->copy()->addDays(4)->setHour(22),
            'city' => 'Los Angeles',
            'address' => 'El Capitan Theatre, Hollywood, CA',
            'latitude' => 34.1019,
            'longitude' => -118.3360,
        ],
        [
            'title' => 'Indiana Jones Adventure Series',
            'description' => 'Complete Indiana Jones film series screening.',
            'category_slug' => 'film',
            'subcategory_slug' => 'adventure',
            'price' => 25.00,
            'dresscode' => 'casual',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(8)->setHour(14),
            'end_datetime' => $now->copy()->addDays(8)->setHour(20),
            'city' => 'London',
            'address' => 'BFI IMAX, London, UK',
            'latitude' => 51.5007,
            'longitude' => -0.1161,
        ],
        [
            'title' => 'Studio Ghibli Festival',
            'description' => 'Weekend of Studio Ghibli animated masterpieces.',
            'category_slug' => 'film',
            'subcategory_slug' => 'animation',
            'price' => 20.00,
            'dresscode' => 'casual',
            'min_age' => 8,
            'start_datetime' => $now->copy()->addDays(12)->setHour(10),
            'end_datetime' => $now->copy()->addDays(14)->setHour(22),
            'city' => 'Tokyo',
            'address' => 'Ghibli Museum, Tokyo, Japan',
            'latitude' => 35.6967,
            'longitude' => 139.5704,
        ],
        [
            'title' => 'Biopic Film Series',
            'description' => 'Award-winning biographical films with historical figures.',
            'category_slug' => 'film',
            'subcategory_slug' => 'biographical',
            'price' => 18.00,
            'dresscode' => 'smart casual',
            'min_age' => 14,
            'start_datetime' => $now->copy()->addDays(6)->setHour(19),
            'end_datetime' => $now->copy()->addDays(6)->setHour(22),
            'city' => 'Boston',
            'address' => 'Museum of Fine Arts, Boston, MA',
            'latitude' => 42.3394,
            'longitude' => -71.0940,
        ],
        [
            'title' => 'Children\'s Film Festival',
            'description' => 'Family-friendly film festival with activities.',
            'category_slug' => 'film',
            'subcategory_slug' => 'children',
            'price' => 12.00,
            'dresscode' => 'casual',
            'min_age' => 5,
            'start_datetime' => $now->copy()->addDays(10)->setHour(10),
            'end_datetime' => $now->copy()->addDays(10)->setHour(16),
            'city' => 'Orlando',
            'address' => 'Disney Springs, Orlando, FL',
            'latitude' => 28.3705,
            'longitude' => -81.5190,
        ],
        [
            'title' => 'Stand-up Comedy Film Night',
            'description' => 'Screening of classic comedy films and stand-up specials.',
            'category_slug' => 'film',
            'subcategory_slug' => 'comedy',
            'price' => 15.00,
            'dresscode' => 'casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(3)->setHour(20),
            'end_datetime' => $now->copy()->addDays(3)->setHour(23),
            'city' => 'Chicago',
            'address' => 'Second City Theater, Chicago, IL',
            'latitude' => 41.9029,
            'longitude' => -87.6343,
        ],
        [
            'title' => 'Film Noir Crime Series',
            'description' => 'Classic film noir detective and crime films.',
            'category_slug' => 'film',
            'subcategory_slug' => 'crime',
            'price' => 20.00,
            'dresscode' => 'smart casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(7)->setHour(19),
            'end_datetime' => $now->copy()->addDays(7)->setHour(23),
            'city' => 'New York',
            'address' => 'Film Forum, New York, NY',
            'latitude' => 40.7336,
            'longitude' => -74.0046,
        ],
        [
            'title' => 'Oscar-Winning Drama Marathon',
            'description' => 'Best Picture winners from the last decade.',
            'category_slug' => 'film',
            'subcategory_slug' => 'drama',
            'price' => 30.00,
            'dresscode' => 'smart casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(9)->setHour(13),
            'end_datetime' => $now->copy()->addDays(9)->setHour(22),
            'city' => 'Los Angeles',
            'address' => 'Academy Museum, Los Angeles, CA',
            'latitude' => 34.0638,
            'longitude' => -118.3595,
        ],
        [
            'title' => 'Lord of the Rings Extended',
            'description' => 'Extended edition trilogy marathon.',
            'category_slug' => 'film',
            'subcategory_slug' => 'fantasy',
            'price' => 40.00,
            'dresscode' => 'casual',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(11)->setHour(11),
            'end_datetime' => $now->copy()->addDays(11)->setHour(23),
            'city' => 'Wellington',
            'address' => 'Embassy Theatre, Wellington, NZ',
            'latitude' => -41.2925,
            'longitude' => 174.7736,
        ],
        [
            'title' => 'Historical Epic Film Festival',
            'description' => 'Grand historical epics on the big screen.',
            'category_slug' => 'film',
            'subcategory_slug' => 'historical',
            'price' => 25.00,
            'dresscode' => 'smart casual',
            'min_age' => 14,
            'start_datetime' => $now->copy()->addDays(13)->setHour(14),
            'end_datetime' => $now->copy()->addDays(13)->setHour(22),
            'city' => 'Rome',
            'address' => 'Cinema dei Piccoli, Rome, Italy',
            'latitude' => 41.9028,
            'longitude' => 12.4964,
        ],

        // 🎭 THEATRE 类别 (12个事件)
        [
            'title' => 'Shakespeare in the Park',
            'description' => 'Open-air performance of Hamlet in central park.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'acting',
            'price' => null,
            'dresscode' => 'casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(5)->setHour(19),
            'end_datetime' => $now->copy()->addDays(5)->setHour(22),
            'city' => 'New York',
            'address' => 'Central Park, New York, NY',
            'latitude' => 40.7829,
            'longitude' => -73.9654,
        ],
        [
            'title' => 'Political Cabaret Show',
            'description' => 'Satirical cabaret poking fun at current politics.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'cabaret',
            'price' => 35.00,
            'dresscode' => 'smart casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(7)->setHour(20),
            'end_datetime' => $now->copy()->addDays(7)->setHour(22),
            'city' => 'Washington D.C.',
            'address' => 'Kennedy Center, Washington D.C.',
            'latitude' => 38.8957,
            'longitude' => -77.0552,
        ],
        [
            'title' => 'Children\'s Puppet Theater',
            'description' => 'Interactive puppet show for young audiences.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'children',
            'price' => 12.00,
            'dresscode' => 'casual',
            'min_age' => 3,
            'start_datetime' => $now->copy()->addDays(9)->setHour(11),
            'end_datetime' => $now->copy()->addDays(9)->setHour(13),
            'city' => 'London',
            'address' => 'Little Angel Theatre, London, UK',
            'latitude' => 51.5365,
            'longitude' => -0.1018,
        ],
        [
            'title' => 'Circus Maximus Revival',
            'description' => 'Modern circus with acrobats and aerial performances.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'circus',
            'price' => 45.00,
            'dresscode' => 'casual',
            'min_age' => 8,
            'start_datetime' => $now->copy()->addDays(11)->setHour(19),
            'end_datetime' => $now->copy()->addDays(11)->setHour(21),
            'city' => 'Montreal',
            'address' => 'Cirque du Soleil Theater, Montreal, Canada',
            'latitude' => 45.5088,
            'longitude' => -73.5617,
        ],
        [
            'title' => 'Improvisational Comedy Night',
            'description' => 'Whose Line Is It Anyway-style improv show.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'comedy',
            'price' => 25.00,
            'dresscode' => 'casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(3)->setHour(20),
            'end_datetime' => $now->copy()->addDays(3)->setHour(22),
            'city' => 'Chicago',
            'address' => 'iO Theater, Chicago, IL',
            'latitude' => 41.9217,
            'longitude' => -87.6531,
        ],
        [
            'title' => 'Tennessee Williams Drama',
            'description' => 'Classic American drama A Streetcar Named Desire.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'drama',
            'price' => 40.00,
            'dresscode' => 'smart casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(8)->setHour(19),
            'end_datetime' => $now->copy()->addDays(8)->setHour(22),
            'city' => 'New Orleans',
            'address' => 'French Quarter Theater, New Orleans, LA',
            'latitude' => 29.9571,
            'longitude' => -90.0630,
        ],
        [
            'title' => 'Avant-Garde Experimental Theater',
            'description' => 'Cutting-edge experimental performance art.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'experimental',
            'price' => 30.00,
            'dresscode' => 'artistic',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(12)->setHour(20),
            'end_datetime' => $now->copy()->addDays(12)->setHour(22),
            'city' => 'Berlin',
            'address' => 'Volksbühne, Berlin, Germany',
            'latitude' => 52.5267,
            'longitude' => 13.4115,
        ],
        [
            'title' => 'Interactive Immersive Theater',
            'description' => 'Audience-participation immersive experience.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'immersive',
            'price' => 55.00,
            'dresscode' => 'comfortable',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(14)->setHour(19),
            'end_datetime' => $now->copy()->addDays(14)->setHour(23),
            'city' => 'London',
            'address' => 'Punchdrunk Theater, London, UK',
            'latitude' => 51.5074,
            'longitude' => -0.1278,
        ],
        [
            'title' => 'Improvisational Theater Workshop',
            'description' => 'Interactive improv workshop for all skill levels.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'improvisational',
            'price' => 35.00,
            'dresscode' => 'casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(6)->setHour(18),
            'end_datetime' => $now->copy()->addDays(6)->setHour(21),
            'city' => 'Los Angeles',
            'address' => 'Upright Citizens Brigade, Los Angeles, CA',
            'latitude' => 34.0837,
            'longitude' => -118.3610,
        ],
        [
            'title' => 'Magic & Illusion Theater',
            'description' => 'Stage magic and illusion performance.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'magic & illusion',
            'price' => 40.00,
            'dresscode' => 'smart casual',
            'min_age' => 10,
            'start_datetime' => $now->copy()->addDays(10)->setHour(20),
            'end_datetime' => $now->copy()->addDays(10)->setHour(22),
            'city' => 'Las Vegas',
            'address' => 'The Mirage, Las Vegas, NV',
            'latitude' => 36.1215,
            'longitude' => -115.1740,
        ],
        [
            'title' => 'Broadway Musical Extravaganza',
            'description' => 'Full-scale Broadway musical production.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'musical',
            'price' => 75.00,
            'dresscode' => 'smart casual',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(16)->setHour(19),
            'end_datetime' => $now->copy()->addDays(16)->setHour(22),
            'city' => 'New York',
            'address' => 'Majestic Theatre, New York, NY',
            'latitude' => 40.7589,
            'longitude' => -73.9851,
        ],
        [
            'title' => 'Stand-Up Comedy Showcase',
            'description' => 'Featured stand-up comedians from Netflix specials.',
            'category_slug' => 'theatre',
            'subcategory_slug' => 'stand up comedy',
            'price' => 30.00,
            'dresscode' => 'casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(4)->setHour(20),
            'end_datetime' => $now->copy()->addDays(4)->setHour(22),
            'city' => 'Los Angeles',
            'address' => 'Laugh Factory, Hollywood, CA',
            'latitude' => 34.0838,
            'longitude' => -118.3689,
        ],

        // 💃 DANCE 类别 (10个事件)
        [
            'title' => 'Swan Lake Ballet',
            'description' => 'Classical ballet performance of Tchaikovsky\'s masterpiece.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'ballet',
            'price' => 60.00,
            'dresscode' => 'formal',
            'min_age' => 8,
            'start_datetime' => $now->copy()->addDays(7)->setHour(19),
            'end_datetime' => $now->copy()->addDays(7)->setHour(22),
            'city' => 'Moscow',
            'address' => 'Bolshoi Theatre, Moscow, Russia',
            'latitude' => 55.7601,
            'longitude' => 37.6185,
        ],
        [
            'title' => 'Ballroom Dance Competition',
            'description' => 'International ballroom dance championship.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'ballroom',
            'price' => 45.00,
            'dresscode' => 'formal',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(12)->setHour(14),
            'end_datetime' => $now->copy()->addDays(12)->setHour(22),
            'city' => 'Blackpool',
            'address' => 'Blackpool Tower Ballroom, UK',
            'latitude' => 53.8142,
            'longitude' => -3.0552,
        ],
        [
            'title' => 'Middle Eastern Dance Festival',
            'description' => 'Traditional and fusion belly dance performances.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'belly dance',
            'price' => 25.00,
            'dresscode' => 'colorful',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(9)->setHour(19),
            'end_datetime' => $now->copy()->addDays(9)->setHour(22),
            'city' => 'Istanbul',
            'address' => 'Hodjapasha Cultural Centre, Istanbul, Turkey',
            'latitude' => 41.0082,
            'longitude' => 28.9784,
        ],
        [
            'title' => 'Breakdance Battle Championship',
            'description' => 'International breakdance competition with cash prizes.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'break',
            'price' => 20.00,
            'dresscode' => 'streetwear',
            'min_age' => 13,
            'start_datetime' => $now->copy()->addDays(5)->setHour(15),
            'end_datetime' => $now->copy()->addDays(5)->setHour(21),
            'city' => 'New York',
            'address' => 'Harlem Dance Theater, New York, NY',
            'latitude' => 40.8116,
            'longitude' => -73.9465,
        ],
        [
            'title' => 'Children\'s Dance Recital',
            'description' => 'Annual children\'s dance school performance.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'children',
            'price' => 15.00,
            'dresscode' => 'casual',
            'min_age' => 3,
            'start_datetime' => $now->copy()->addDays(8)->setHour(18),
            'end_datetime' => $now->copy()->addDays(8)->setHour(20),
            'city' => 'Orlando',
            'address' => 'Dr. Phillips Center, Orlando, FL',
            'latitude' => 28.5384,
            'longitude' => -81.3789,
        ],
        [
            'title' => 'Contemporary Dance Festival',
            'description' => 'Cutting-edge contemporary dance performances.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'contemporary',
            'price' => 35.00,
            'dresscode' => 'artistic',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(11)->setHour(20),
            'end_datetime' => $now->copy()->addDays(11)->setHour(22),
            'city' => 'Paris',
            'address' => 'Centre Pompidou, Paris, France',
            'latitude' => 48.8606,
            'longitude' => 2.3522,
        ],
        [
            'title' => 'Country Line Dancing Night',
            'description' => 'Traditional country line dancing with live band.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'country',
            'price' => 18.00,
            'dresscode' => 'western',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(4)->setHour(20),
            'end_datetime' => $now->copy()->addDays(4)->setHour(23),
            'city' => 'Nashville',
            'address' => 'Wildhorse Saloon, Nashville, TN',
            'latitude' => 36.1627,
            'longitude' => -86.7816,
        ],
        [
            'title' => 'International Folk Dance',
            'description' => 'Traditional folk dances from around the world.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'folk',
            'price' => 22.00,
            'dresscode' => 'traditional',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(14)->setHour(19),
            'end_datetime' => $now->copy()->addDays(14)->setHour(22),
            'city' => 'Edinburgh',
            'address' => 'Edinburgh Festival Theatre, Scotland',
            'latitude' => 55.9471,
            'longitude' => -3.1859,
        ],
        [
            'title' => 'Hip Hop Dance Battle',
            'description' => 'Street-style hip hop dance competition.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'hip hop',
            'price' => 20.00,
            'dresscode' => 'streetwear',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(6)->setHour(18),
            'end_datetime' => $now->copy()->addDays(6)->setHour(22),
            'city' => 'Los Angeles',
            'address' => 'Millennium Dance Complex, Los Angeles, CA',
            'latitude' => 34.0838,
            'longitude' => -118.3610,
        ],
        [
            'title' => 'Jazz Dance Workshop',
            'description' => 'Professional jazz dance classes and performance.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'jazz',
            'price' => 30.00,
            'dresscode' => 'dancewear',
            'min_age' => 14,
            'start_datetime' => $now->copy()->addDays(10)->setHour(10),
            'end_datetime' => $now->copy()->addDays(10)->setHour(16),
            'city' => 'New York',
            'address' => 'Broadway Dance Center, New York, NY',
            'latitude' => 40.7610,
            'longitude' => -73.9866,
        ],

        // 👥 COMMUNITY 类别 (8个事件)
        [
            'title' => 'Rio Carnival Celebration',
            'description' => 'Annual carnival parade with samba schools.',
            'category_slug' => 'community',
            'subcategory_slug' => 'carnival',
            'price' => 50.00,
            'dresscode' => 'costume',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(20)->setHour(10),
            'end_datetime' => $now->copy()->addDays(20)->setHour(23),
            'city' => 'Rio de Janeiro',
            'address' => 'Sambadrome Marquês de Sapucaí, Rio, Brazil',
            'latitude' => -22.9122,
            'longitude' => -43.2302,
        ],
        [
            'title' => 'Children\'s Science Fair',
            'description' => 'Interactive science exhibits for children.',
            'category_slug' => 'community',
            'subcategory_slug' => 'children',
            'price' => null,
            'dresscode' => 'casual',
            'min_age' => 5,
            'start_datetime' => $now->copy()->addDays(8)->setHour(10),
            'end_datetime' => $now->copy()->addDays(8)->setHour(16),
            'city' => 'Boston',
            'address' => 'Boston Children\'s Museum, Boston, MA',
            'latitude' => 42.3488,
            'longitude' => -71.0471,
        ],
        [
            'title' => 'Christmas Market Festival',
            'description' => 'Traditional German Christmas market with crafts.',
            'category_slug' => 'community',
            'subcategory_slug' => 'christmas market',
            'price' => null,
            'dresscode' => 'warm',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(40)->setHour(11),
            'end_datetime' => $now->copy()->addDays(40)->setHour(21),
            'city' => 'Munich',
            'address' => 'Marienplatz, Munich, Germany',
            'latitude' => 48.1372,
            'longitude' => 11.5755,
        ],
        [
            'title' => 'County Fair & Rodeo',
            'description' => 'Traditional county fair with rides and rodeo.',
            'category_slug' => 'community',
            'subcategory_slug' => 'fair',
            'price' => 25.00,
            'dresscode' => 'casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(15)->setHour(10),
            'end_datetime' => $now->copy()->addDays(15)->setHour(22),
            'city' => 'Cheyenne',
            'address' => 'Cheyenne Frontier Days, WY',
            'latitude' => 41.1400,
            'longitude' => -104.8202,
        ],
        [
            'title' => 'International Food Festival',
            'description' => 'Cuisine from around the world with live cooking.',
            'category_slug' => 'community',
            'subcategory_slug' => 'food & drink',
            'price' => 30.00,
            'dresscode' => 'casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(12)->setHour(12),
            'end_datetime' => $now->copy()->addDays(12)->setHour(20),
            'city' => 'San Francisco',
            'address' => 'Ferry Building Marketplace, San Francisco, CA',
            'latitude' => 37.7955,
            'longitude' => -122.3937,
        ],
        [
            'title' => 'City Light Show Spectacular',
            'description' => 'Annual light and projection mapping show.',
            'category_slug' => 'community',
            'subcategory_slug' => 'light show',
            'price' => null,
            'dresscode' => 'casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(18)->setHour(20),
            'end_datetime' => $now->copy()->addDays(18)->setHour(23),
            'city' => 'Sydney',
            'address' => 'Sydney Opera House, Sydney, Australia',
            'latitude' => -33.8568,
            'longitude' => 151.2153,
        ],
        [
            'title' => 'Oktoberfest Celebration',
            'description' => 'Traditional German beer festival.',
            'category_slug' => 'community',
            'subcategory_slug' => 'oktoberfest',
            'price' => 40.00,
            'dresscode' => 'traditional',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(25)->setHour(11),
            'end_datetime' => $now->copy()->addDays(25)->setHour(23),
            'city' => 'Munich',
            'address' => 'Theresienwiese, Munich, Germany',
            'latitude' => 48.1315,
            'longitude' => 11.5496,
        ],
        [
            'title' => 'Community Sports Day',
            'description' => 'Local sports competitions and activities.',
            'category_slug' => 'community',
            'subcategory_slug' => 'sports',
            'price' => null,
            'dresscode' => 'sportswear',
            'min_age' => null,
            'start_datetime' => $now->copy()->addDays(9)->setHour(9),
            'end_datetime' => $now->copy()->addDays(9)->setHour(17),
            'city' => 'Portland',
            'address' => 'Portland Parks & Recreation, Portland, OR',
            'latitude' => 45.5231,
            'longitude' => -122.6765,
        ],

        // 🎵 MUSIC 类别 (10个事件)
        [
            'title' => 'Alternative Rock Festival',
            'description' => 'Three-day alternative rock music festival.',
            'category_slug' => 'music',
            'subcategory_slug' => 'alternative',
            'price' => 120.00,
            'dresscode' => 'festival wear',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(22)->setHour(14),
            'end_datetime' => $now->copy()->addDays(24)->setHour(23),
            'city' => 'Seattle',
            'address' => 'The Gorge Amphitheatre, George, WA',
            'latitude' => 47.0951,
            'longitude' => -119.9705,
        ],
        [
            'title' => 'Blues & Roots Festival',
            'description' => 'Traditional blues and roots music festival.',
            'category_slug' => 'music',
            'subcategory_slug' => 'blues',
            'price' => 65.00,
            'dresscode' => 'casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(14)->setHour(15),
            'end_datetime' => $now->copy()->addDays(14)->setHour(23),
            'city' => 'Memphis',
            'address' => 'Beale Street, Memphis, TN',
            'latitude' => 35.1382,
            'longitude' => -90.0526,
        ],
        [
            'title' => 'Children\'s Music Concert',
            'description' => 'Interactive music concert for young children.',
            'category_slug' => 'music',
            'subcategory_slug' => 'children',
            'price' => 15.00,
            'dresscode' => 'casual',
            'min_age' => 3,
            'start_datetime' => $now->copy()->addDays(6)->setHour(10),
            'end_datetime' => $now->copy()->addDays(6)->setHour(12),
            'city' => 'Chicago',
            'address' => 'Chicago Children\'s Museum, Chicago, IL',
            'latitude' => 41.8917,
            'longitude' => -87.6086,
        ],
        [
            'title' => 'Classic Pop Revival Concert',
            'description' => '80s and 90s pop music tribute concert.',
            'category_slug' => 'music',
            'subcategory_slug' => 'classic pop',
            'price' => 45.00,
            'dresscode' => 'retro',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(11)->setHour(20),
            'end_datetime' => $now->copy()->addDays(11)->setHour(23),
            'city' => 'Los Angeles',
            'address' => 'Hollywood Bowl, Los Angeles, CA',
            'latitude' => 34.1122,
            'longitude' => -118.3393,
        ],
        [
            'title' => 'Symphony Orchestra Concert',
            'description' => 'Classical music concert featuring Beethoven.',
            'category_slug' => 'music',
            'subcategory_slug' => 'concert',
            'price' => 55.00,
            'dresscode' => 'formal',
            'min_age' => 8,
            'start_datetime' => $now->copy()->addDays(8)->setHour(20),
            'end_datetime' => $now->copy()->addDays(8)->setHour(22),
            'city' => 'Vienna',
            'address' => 'Musikverein, Vienna, Austria',
            'latitude' => 48.2008,
            'longitude' => 16.3731,
        ],
        [
            'title' => 'Contemporary Music Festival',
            'description' => 'Modern classical and contemporary compositions.',
            'category_slug' => 'music',
            'subcategory_slug' => 'contemporary',
            'price' => 40.00,
            'dresscode' => 'smart casual',
            'min_age' => 16,
            'start_datetime' => $now->copy()->addDays(16)->setHour(19),
            'end_datetime' => $now->copy()->addDays(16)->setHour(22),
            'city' => 'Berlin',
            'address' => 'Berliner Philharmonie, Berlin, Germany',
            'latitude' => 52.5104,
            'longitude' => 13.3697,
        ],
        [
            'title' => 'Country Music Jamboree',
            'description' => 'Traditional country music festival.',
            'category_slug' => 'music',
            'subcategory_slug' => 'country',
            'price' => 50.00,
            'dresscode' => 'western',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(13)->setHour(14),
            'end_datetime' => $now->copy()->addDays(13)->setHour(23),
            'city' => 'Nashville',
            'address' => 'Grand Ole Opry, Nashville, TN',
            'latitude' => 36.1589,
            'longitude' => -86.7946,
        ],
        [
            'title' => 'Disco Night Fever',
            'description' => '70s disco revival party with live DJ.',
            'category_slug' => 'music',
            'subcategory_slug' => 'disco',
            'price' => 30.00,
            'dresscode' => 'disco',
            'min_age' => 21,
            'start_datetime' => $now->copy()->addDays(5)->setHour(21),
            'end_datetime' => $now->copy()->addDays(6)->setHour(2),
            'city' => 'New York',
            'address' => 'Studio 54, New York, NY',
            'latitude' => 40.7639,
            'longitude' => -73.9794,
        ],
        [
            'title' => 'Electronic Dance Music Festival',
            'description' => 'Major EDM festival with international DJs.',
            'category_slug' => 'music',
            'subcategory_slug' => 'edm electronic dance music',
            'price' => 150.00,
            'dresscode' => 'festival wear',
            'min_age' => 18,
            'start_datetime' => $now->copy()->addDays(30)->setHour(16),
            'end_datetime' => $now->copy()->addDays(32)->setHour(23),
            'city' => 'Las Vegas',
            'address' => 'Las Vegas Motor Speedway, Las Vegas, NV',
            'latitude' => 36.2723,
            'longitude' => -115.0102,
        ],
        [
            'title' => 'Folk Music Gathering',
            'description' => 'Traditional and contemporary folk music.',
            'category_slug' => 'music',
            'subcategory_slug' => 'folk',
            'price' => 25.00,
            'dresscode' => 'casual',
            'min_age' => 12,
            'start_datetime' => $now->copy()->addDays(9)->setHour(19),
            'end_datetime' => $now->copy()->addDays(9)->setHour(22),
            'city' => 'Dublin',
            'address' => 'Temple Bar District, Dublin, Ireland',
            'latitude' => 53.3458,
            'longitude' => -6.2639,
        ],
        [
            'title' => 'Rotterdam Dance Festival',
            'description' => 'Three days of contemporary dance performances featuring international choreographers.',
            'category_slug' => 'dance',
            'subcategory_slug' => 'contemporary',
            'price' => 45.00,
            'dresscode' => 'casual',
            'min_age' => null,
            'start_datetime' => $now->copy()->subHours(1),
            'end_datetime' => $now->copy()->addHours(5),
            'city' => 'Rotterdam',
            'address' => 'Schouwburgplein 25, 3012 CL Rotterdam',
            'latitude' => 51.9225,
            'longitude' => 4.4792,
            'afternoon' => true,
            'evening' => true,
        ],
        [
            'title' => 'Amsterdam Jazz Night',
            'description' => 'An evening of smooth jazz featuring local and international artists at the iconic Paradiso.',
            'category_slug' => 'music',
            'subcategory_slug' => 'jazz',
            'price' => 35.00,
            'dresscode' => 'smart casual',
            'min_age' => 18,
            'start_datetime' => $now->copy()->subHours(2),
            'end_datetime' => $now->copy()->addHours(3),
            'city' => 'Amsterdam',
            'address' => 'Weteringsschans 6-8, 1017 SG Amsterdam',
            'latitude' => 52.3622,
            'longitude' => 4.8839,
            'evening' => true,
        ],
    ];

        foreach ($events as $eventData) {
            $latitude = $eventData['latitude'];
            $longitude = $eventData['longitude'];
            
            // Get category ID from slug
            $category = Category::where('slug', $eventData['category_slug'])->first();
            $categoryId = $category ? $category->id : null;
            
            // Get subcategory ID from slug if provided
            $subcategorySlug = $eventData['subcategory_slug'] ?? null;
            $subcategoryId = null;
            if ($subcategorySlug && $categoryId) {
                $subcategory = SubCategory::where('category_id', $categoryId)
                    ->where('slug', $subcategorySlug)
                    ->first();
                $subcategoryId = $subcategory ? $subcategory->id : null;
            }

            // Prepare event data
            $eventInsertData = [
                'title' => $eventData['title'],
                'description' => $eventData['description'],
                'category_id' => $categoryId,
                'subcategory_id' => $subcategoryId,
                'price' => $eventData['price'],
                'dresscode' => $eventData['dresscode'],
                'min_age' => $eventData['min_age'],
                'start_datetime' => $eventData['start_datetime']->toDateTimeString(),
                'end_datetime' => $eventData['end_datetime']->toDateTimeString(),
                'city' => $eventData['city'],
                'address' => $eventData['address'],
                'is_published' => true,
                'morning' => $eventData['morning'] ?? false,
                'afternoon' => $eventData['afternoon'] ?? false,
                'evening' => $eventData['evening'] ?? false,
                'night' => $eventData['night'] ?? false,
                'created_at' => $now->toDateTimeString(),
                'updated_at' => $now->toDateTimeString(),
            ];

            // Insert event with location data based on database type
            if (DB::getDriverName() === 'pgsql') {
                // PostgreSQL with PostGIS
                DB::table('events')->insert(array_merge($eventInsertData, [
                    'location' => DB::raw("ST_SetSRID(ST_MakePoint({$longitude}, {$latitude}), 4326)::geography"),
                ]));
            } else {
                // SQLite and other databases - use latitude and longitude columns
                DB::table('events')->insert(array_merge($eventInsertData, [
                    'latitude' => $latitude,
                    'longitude' => $longitude,
                ]));
            }
        }

        $this->command->info('Seeded ' . count($events) . ' events across Amsterdam, Rotterdam, Utrecht, and Berlin.');
    }
}
